[package]
name = "options-man"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = { version = "2.7.2", features = ["pretty-print"] }
pest_derive = "2.7.2"
